services:
  db:
    image: mariadb:10.6
    container_name: medibot-db
    command: --innodb_buffer_pool_size=512M --innodb_flush_log_at_trx_commit=2 --innodb_log_buffer_size=64M
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medibot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - medibot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: medibot-pma
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - medibot-network

  backend:
    build: ./backend
    container_name: medibot-backend
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/var
      - /var/www/html/vendor
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/medibot?serverVersion=10.6.12-MariaDB&charset=utf8mb4"
      DEFAULT_URI: "http://localhost:8000"
      APP_ENV: "dev"
      APP_DEBUG: "1" # Desactivar debug extremo para mejorar respuesta
    depends_on:
      - db
    networks:
      - medibot-network

  frontend:
    build: ./frontend
    container_name: medibot-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - medibot-network

  n8n:
    image: n8nio/n8n:latest
    container_name: medibot-n8n
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=https://gyvvv-5-180-250-196.a.free.pinggy.link/
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,node-fetch
      - N8N_BLOCK_SVG_DOM_PARSER=false
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - medibot-network

volumes:
  db_data:
  n8n_data:


networks:
  medibot-network:
    driver: bridge
